Repository AY2122S2-CS2103T-T13-2/tp, pull requests merged in 2022-04, with the labels that each got.

#214 Change WeekId value from String to Integer
  src/main/java/seedu/address/model/lesson/WeekId.java
  src/main/java/seedu/address/model/studentattendance/Attendance.java
  src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/ui/LessonCard.java
Labels: priority.High

#215 Fix PE-D bugs
  src/main/java/seedu/address/logic/commands/DisenrolCommand.java
  src/main/java/seedu/address/logic/commands/EnrolCommand.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High

#212 PE-D Bug fixes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/assessment/Assessment.java
  src/main/java/seedu/address/model/assessment/Grade.java
  src/main/java/seedu/address/model/tamodule/ModuleCode.java
  src/main/java/seedu/address/model/tamodule/ModuleName.java
Labels: type.Bug, priority.High

#218 Create method to check if student exists using studentId
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TAssist.java
Labels: priority.High, Integration

#220 Draft PPP
  docs/team/jxt00.md
Labels: type.Task, priority.High

#142 Add v1.3 user stories and use cases to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, Documentation

#223 Update PPP
  docs/team/wxliong.md
Labels: type.Task, priority.High

#224 Update PPP
  docs/team/lkldev.md
Labels: type.Task, priority.High

#222 Add tests for ClassGroup/JsonAdaptedClassGroup, Delete
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/classgroup/ClassGroupType.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedStudentAttendance.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAB3CommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAB3CommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ListAB3CommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteAB3CommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/classgroup/ClassGroupIdTest.java
  src/test/java/seedu/address/model/classgroup/ClassGroupTest.java
  src/test/java/seedu/address/model/classgroup/UniqueClassGroupListTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/model/lesson/WeekIdTest.java
  src/test/java/seedu/address/model/studentattendance/AttendanceTest.java
  src/test/java/seedu/address/model/studentattendance/StudentAttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClassGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentAttendanceTest.java
  src/test/java/seedu/address/testutil/ClassGroupBuilder.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
  src/test/java/seedu/address/testutil/StudentAttendanceBuilder.java
  src/test/java/seedu/address/testutil/TypicalClassGroups.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
  src/test/java/seedu/address/testutil/TypicalStudentAttendances.java
Labels: type.Task, priority.High

#225 Update PPP v2
  docs/team/wxliong.md
Labels: type.Task, priority.High

#226 Updated PPP v2
  docs/team/jxt00.md
Labels: type.Task, priority.High

#216 Fix PE-D bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High, DO NOT MERGE

#228 Add testing for Student attributes and JsonAdaptedStudent
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/DisenrolCommandTest.java
  src/test/java/seedu/address/logic/commands/EnrolCommandTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/NameTest.java
  src/test/java/seedu/address/model/student/StudentIdTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/TelegramTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: type.Task, priority.High

#233 Fix bugs where storage lessons are not validated
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudentAttendance.java
  src/test/java/seedu/address/storage/JsonAdaptedClassGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentAttendanceTest.java
Labels: type.Bug, priority.High

#232 Update testcases
  .github/workflows/gradle.yml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/classgroup/ClassGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClassGroupTest.java
  src/test/java/seedu/address/testutil/AssessmentBuilder.java
  src/test/java/seedu/address/testutil/ClassGroupBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssessments.java
  src/test/java/seedu/address/testutil/TypicalClassGroups.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalStudentAttendances.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalTAssist.java
Labels: type.Task, priority.High

#235 Test model manager
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: DO NOT MERGE

#230 Update Docs (UG/DG/PPP)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EnrolActivityDiagram.puml
  docs/diagrams/EnrolModelSequenceDiagram.puml
  docs/diagrams/EnrolSequenceDiagram.puml
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/MarkUnmarkActivityDiagram.puml
  docs/diagrams/MarkUnmarkState1.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/EnrolActivityDiagram.png
  docs/images/EnrolModelSequenceDiagram.png
  docs/images/EnrolSequenceDiagram.png
  docs/images/ListActivityDiagram.png
  docs/images/MarkUnmarkActivityDiagram.png
  docs/images/MarkUnmarkState1.png
  docs/images/StorageClassDiagram.png
  docs/team/gernene.md
  docs/team/jxt00.md
  docs/team/lkldev.md
  docs/team/wxliong.md
Labels: Documentation
