Repository AY2122S2-CS2103T-T13-2/tp, pull requests merged in 2022-03, with the labels that each got.

#35 Update DG with use cases for Student
  docs/DeveloperGuide.md
Labels: Documentation

#36 Update UserGuide and upload profile picture
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/mengan.png
Labels: type.Task

#37 Update NFR and Glossary in DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Task

#38 Fix use case naming convention in DG
  docs/DeveloperGuide.md
Labels: Documentation

#39 Rename profile picture
  docs/AboutUs.md
  docs/images/evaderfati.png
Labels: type.Task

#41 Fix discrepancies in uses cases in DG
  docs/DeveloperGuide.md
Labels: Documentation

#48 Create Module entity and its attributes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/EntityType.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
Labels: type.Task

#50 Create model classes for Student, its attributes and UniqueStudentList
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentID.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
Labels: type.Task

#52 Remove tags in Student class
  src/main/java/seedu/address/model/student/Student.java
Labels: type.Task

#47 Add models for Class Group, its attributes and UniqueClassGroupList
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/classgroup/ClassGroupId.java
  src/main/java/seedu/address/model/classgroup/ClassGroupType.java
  src/main/java/seedu/address/model/classgroup/UniqueClassGroupList.java
  src/main/java/seedu/address/model/classgroup/exceptions/ClassGroupNotFoundException.java
  src/main/java/seedu/address/model/classgroup/exceptions/DuplicateClassGroupException.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleName.java
Labels: type.Task

#54 Fix coding standards for StudentId
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
Labels: type.Task

#56 Update ClassGroupID regex and edit some Javadocs and methods
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/classgroup/ClassGroupId.java
  src/main/java/seedu/address/model/classgroup/ClassGroupType.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/tamodule/ModuleCode.java
  src/main/java/seedu/address/model/tamodule/ModuleName.java
  src/main/java/seedu/address/model/tamodule/UniqueModuleList.java
Labels: type.Task

#58 Add tests for ClassGroup, ClassGroupId and UniqueClassGroupList
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/classgroup/ClassGroupIdTest.java
  src/test/java/seedu/address/model/classgroup/ClassGroupTest.java
  src/test/java/seedu/address/model/classgroup/UniqueClassGroupListTest.java
  src/test/java/seedu/address/testutil/ClassGroupBuilder.java
  src/test/java/seedu/address/testutil/TypicalClassGroups.java
Labels: type.Task, priority.High

#61 Modify common classes to be compatible with TAssist
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/EntityType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTAssist.java
  src/main/java/seedu/address/model/TAssist.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/entity/Entity.java
  src/main/java/seedu/address/model/entity/EntityConverter.java
  src/main/java/seedu/address/model/entity/EntityType.java
  src/main/java/seedu/address/model/entity/exceptions/DifferentEntityException.java
  src/main/java/seedu/address/model/entity/exceptions/InvalidEntityConversionException.java
  src/main/java/seedu/address/model/entity/exceptions/UnknownEntityException.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tamodule/TaModule.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: Integration

#67 Change ClassGroup to use TaModule instead of ModuleCode
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/test/java/seedu/address/model/classgroup/ClassGroupTest.java
  src/test/java/seedu/address/model/classgroup/UniqueClassGroupListTest.java
  src/test/java/seedu/address/testutil/ClassGroupBuilder.java
  src/test/java/seedu/address/testutil/TypicalClassGroups.java
Labels: type.Task, priority.High

#64 Update ACADEMIC_YEAR for Module and types for ClassGroup in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Documentation

#77 Add toString() to ClassGroupType
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/classgroup/ClassGroupType.java
Labels: type.Task

#80 Change phone number field to Telegram handle for Student entity
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task, priority.High

#81 Update documentation for Academic Year in UG
  docs/UserGuide.md
Labels: Documentation

#85 Create JsonAdaptedStudent for storage component
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Task

#86 Update retrieving of Telegram value
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Task

#88 Add storage for ClassGroup
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
Labels: type.Task, priority.High

#89 Fix optional Telegram handle value
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Task

#93 Check that module exists before creating ClassGroup from JSON
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
Labels: type.Task, priority.High

#91 Update storage to work with all three entities
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableTAssist.java
  src/main/java/seedu/address/storage/JsonTAssistStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TAssistStorage.java
Labels: type.Task, priority.High, Integration

#97 Finalize v1.2
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TAssistParser.java
  src/main/java/seedu/address/model/classgroup/ClassGroupId.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tamodule/ModuleCode.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, Documentation, Integration

#106 Add Lesson and StudentAttendance as well as author tags
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/classgroup/ClassGroupId.java
  src/main/java/seedu/address/model/classgroup/ClassGroupType.java
  src/main/java/seedu/address/model/classgroup/UniqueClassGroupList.java
  src/main/java/seedu/address/model/classgroup/exceptions/ClassGroupNotFoundException.java
  src/main/java/seedu/address/model/classgroup/exceptions/DuplicateClassGroupException.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/WeekId.java
  src/main/java/seedu/address/model/studentattendance/Attendance.java
  src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
Labels: type.Task, priority.High

#110 Add delete feature and update Model component in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassGroupClassDiagram.puml
  docs/diagrams/BetterModelStudentClassDiagram.puml
  docs/diagrams/BetterModelTaModuleClassDiagram.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteState0.puml
  docs/diagrams/DeleteState1.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/images/AB3ModelClassDiagram.png
  docs/images/BetterModelClassGroupClassDiagram.png
  docs/images/BetterModelStudentClassDiagram.png
  docs/images/BetterModelTaModuleClassDiagram.png
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteState0.png
  docs/images/DeleteState1.png
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High, Documentation

#115 Update delete TAModule command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/TAssist.java
  src/main/java/seedu/address/model/classgroup/UniqueClassGroupList.java
Labels: type.Bug

#120 Update App version and enable assertions in gradle
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#113 Add 'add' and 'enrol' implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/AddState0.puml
  docs/diagrams/AddState1.puml
  docs/diagrams/AddState2.puml
  docs/diagrams/EnrolState1.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/AddState0.png
  docs/images/AddState1.png
  docs/images/AddState2.png
  docs/images/EnrolState1.png
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/Telegram.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Task, priority.High, Documentation

#112 Add v1.3 features to UG and Assessment to Model component in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelAssessmentClassDiagram.puml
  docs/diagrams/BetterModelTaModuleClassDiagram.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteState0.puml
  docs/diagrams/DeleteState1.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelAssessmentClassDiagram.png
  docs/images/BetterModelTaModuleClassDiagram.png
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteState0.png
  docs/images/DeleteState1.png
  docs/images/ModelClassDiagram.png
  docs/images/Ui.png
  docs/images/Ui_mockup.png
Labels: type.Task, priority.High, Documentation

#124 Add List Command to DG
  docs/DeveloperGuide.md
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ListState0.puml
  docs/diagrams/ListState1.puml
  docs/images/ListActivityDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/ListState0.png
  docs/images/ListState1.png
Labels: type.Task, priority.High, Documentation

#123 Add Grade command to DG
  docs/DeveloperGuide.md
  docs/diagrams/GradeActivityDiagram.puml
  docs/diagrams/GradeAssessmentSequenceDiagram.puml
  docs/diagrams/GradeSequenceDiagram.puml
  docs/diagrams/GradeState0.puml
  docs/diagrams/GradeState1.puml
  docs/images/GradeActivityDiagram.png
  docs/images/GradeAssessmentSequenceDiagram.png
  docs/images/GradeSequenceDiagram.png
  docs/images/GradeState0.png
  docs/images/GradeState1.png
Labels: type.Task, priority.High, Documentation

#122 Creates assessment entity
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTAssist.java
  src/main/java/seedu/address/model/TAssist.java
  src/main/java/seedu/address/model/assessment/Assessment.java
  src/main/java/seedu/address/model/assessment/AssessmentName.java
  src/main/java/seedu/address/model/assessment/Grade.java
  src/main/java/seedu/address/model/assessment/SimpleName.java
  src/main/java/seedu/address/model/assessment/UniqueAssessmentList.java
  src/main/java/seedu/address/model/assessment/exceptions/AssessmentNotFoundException.java
  src/main/java/seedu/address/model/assessment/exceptions/DuplicateAssessmentException.java
  src/main/java/seedu/address/model/entity/EntityConverter.java
  src/main/java/seedu/address/model/entity/EntityType.java
  src/main/java/seedu/address/model/tamodule/TaModule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High, Integration

#137 Add find feature to UG
  docs/UserGuide.md
Labels: type.Task, priority.High, Documentation

#139 Update common classes
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/tamodule/TaModule.java
Labels: priority.High, Integration

#134 Add parsing for mark and unmark command
  src/main/java/seedu/address/logic/commands/DisenrolCommand.java
  src/main/java/seedu/address/logic/commands/EnrolCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TAssistParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
Labels: type.Task, priority.High

#138 Add storage for Assessment, update storage for Module
  src/main/java/seedu/address/storage/JsonAdaptedAssessment.java
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedTaModule.java
  src/main/java/seedu/address/storage/JsonSerializableTAssist.java
Labels: type.Task, priority.High

#146 Add enrol and disenrol feature
  src/main/java/seedu/address/logic/commands/DisenrolCommand.java
  src/main/java/seedu/address/logic/commands/EnrolCommand.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/tamodule/TaModule.java
Labels: type.Task, priority.High

#150 Add mark/unmark feature
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/WeekId.java
  src/main/java/seedu/address/model/studentattendance/Attendance.java
  src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
Labels: type.Task, priority.High

#156 Fix misc bugs
  src/main/java/seedu/address/logic/commands/DisenrolCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/GradeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TAssist.java
  src/main/java/seedu/address/model/assessment/Assessment.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/studentattendance/Attendance.java
  src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
  src/main/java/seedu/address/model/tamodule/TaModule.java
  src/main/java/seedu/address/storage/JsonAdaptedClassGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedStudentAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedTaModule.java
Labels: priority.High, Integration

#159 Fix mark/unmark bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MarkUnmarkSequenceDiagram.puml
  docs/images/MarkUnmarkSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/classgroup/ClassGroup.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/studentattendance/Attendance.java
  src/main/java/seedu/address/model/studentattendance/StudentAttendance.java
Labels: type.Bug, priority.High

#141 Update UG on format list/filter and add caution to delete
  docs/UserGuide.md
  docs/_config.yml
Labels: Documentation
